#!/bin/sh
set -eu

PROJECT_ROOT="$(CDPATH='' cd -- "$(dirname "$0")/../.." && pwd)"
TEST_PROJECT_ROOT="$PROJECT_ROOT"

FEATURES=""
IMAGES=""
FEATURES_EXPLICIT='false'
IMAGES_EXPLICIT='false'
RUN_AUTOGENERATED='true'
RUN_SCENARIOS='true'
DRY_RUN='false'
QUIET='false'
LOG_LEVEL='info'
LIST_MODE=''
FILTERED_PROJECT=''

cleanup() {
    if [ -n "$FILTERED_PROJECT" ] && [ -d "$FILTERED_PROJECT" ]; then
        rm -rf "$FILTERED_PROJECT"
    fi
}
trap cleanup EXIT HUP INT TERM

usage() {
    cat <<'EOF'
Usage: npm test -- [options]

Test every Feature against every image declared in its scenarios.json by
default. Feature and image filters may be repeated.

Options:
  -f, --feature ID       Test only this Feature (repeatable)
  -i, --image IMAGE      Test only this base image (repeatable)
      --scenarios-only   Run scenario tests only
      --skip-scenarios   Run autogenerated tests only
      --log-level LEVEL  Dev Container CLI log level: info, debug, or trace
  -q, --quiet            Reduce Dev Container CLI output
      --dry-run          Print commands without running containers
      --list-features    Print the selected Feature IDs and exit
      --list-images      Print the selected images and exit
      --list-images-json Print the selected images as a JSON array and exit
  -h, --help             Show this help

Examples:
  npm test
  npm test -- --feature codex
  npm test -- --image ubuntu:24.04
  npm test -- -f codex -i alpine:3.23
EOF
}

append_value() {
    current_values="$1"
    new_value="$2"
    if [ -n "$current_values" ]; then
        printf '%s\n%s\n' "$current_values" "$new_value"
    else
        printf '%s\n' "$new_value"
    fi
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        -f | --feature)
            [ "$#" -ge 2 ] || {
                printf 'Missing value for %s\n' "$1" >&2
                exit 2
            }
            FEATURES="$(append_value "$FEATURES" "$2")"
            FEATURES_EXPLICIT='true'
            shift 2
            ;;
        -i | --image)
            [ "$#" -ge 2 ] || {
                printf 'Missing value for %s\n' "$1" >&2
                exit 2
            }
            IMAGES="$(append_value "$IMAGES" "$2")"
            IMAGES_EXPLICIT='true'
            shift 2
            ;;
        --scenarios-only)
            RUN_AUTOGENERATED='false'
            shift
            ;;
        --skip-scenarios)
            RUN_SCENARIOS='false'
            shift
            ;;
        --log-level)
            [ "$#" -ge 2 ] || {
                printf 'Missing value for %s\n' "$1" >&2
                exit 2
            }
            LOG_LEVEL="$2"
            shift 2
            ;;
        -q | --quiet)
            QUIET='true'
            shift
            ;;
        --dry-run)
            DRY_RUN='true'
            shift
            ;;
        --list-features | --list-images | --list-images-json)
            LIST_MODE="$1"
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            printf 'Unknown option: %s\n\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

case "$LOG_LEVEL" in
    info | debug | trace) ;;
    *)
        printf 'Invalid log level: %s (expected info, debug, or trace)\n' "$LOG_LEVEL" >&2
        exit 2
        ;;
esac

if [ "$RUN_AUTOGENERATED" = 'false' ] && [ "$RUN_SCENARIOS" = 'false' ]; then
    printf '%s\n' 'Cannot combine --scenarios-only and --skip-scenarios.' >&2
    exit 2
fi

if [ "$FEATURES_EXPLICIT" = 'false' ]; then
    for feature_dir in "$PROJECT_ROOT"/src/*; do
        [ -d "$feature_dir" ] || continue
        [ -f "$feature_dir/devcontainer-feature.json" ] || continue
        FEATURES="$(append_value "$FEATURES" "$(basename "$feature_dir")")"
    done
fi

[ -n "$FEATURES" ] || {
    printf 'No Features found under %s/src.\n' "$PROJECT_ROOT" >&2
    exit 1
}

if [ -n "${TMPDIR:-}" ]; then
    mkdir -p "$TMPDIR"
fi

for feature in $FEATURES; do
    if [ ! -f "$PROJECT_ROOT/src/$feature/devcontainer-feature.json" ]; then
        printf 'Unknown Feature: %s\n' "$feature" >&2
        exit 2
    fi
    if [ ! -f "$PROJECT_ROOT/test/$feature/test.sh" ]; then
        printf 'Feature %s has no test/%s/test.sh.\n' "$feature" "$feature" >&2
        exit 1
    fi
done

collect_images() {
    set --
    for scenarios_file in "$PROJECT_ROOT"/test/*/scenarios.json; do
        [ -f "$scenarios_file" ] || continue
        set -- "$@" "$scenarios_file"
    done

    [ "$#" -gt 0 ] || return 0
    node -e '
        const fs = require("fs");
        const images = new Set();
        for (const file of process.argv.slice(1)) {
            const scenarios = JSON.parse(fs.readFileSync(file, "utf8"));
            for (const scenario of Object.values(scenarios)) {
                if (typeof scenario.image === "string") images.add(scenario.image);
            }
        }
        process.stdout.write([...images].join("\n"));
    ' "$@"
}

if [ "$IMAGES_EXPLICIT" = 'false' ]; then
    IMAGES="$(collect_images)"
fi

case "$LIST_MODE" in
    --list-features)
        printf '%s\n' "$FEATURES"
        exit 0
        ;;
    --list-images)
        [ -n "$IMAGES" ] && printf '%s\n' "$IMAGES"
        exit 0
        ;;
    --list-images-json)
        printf '%s\n' "$IMAGES" | node -e '
            const input = require("fs").readFileSync(0, "utf8").trim();
            process.stdout.write(JSON.stringify(input ? input.split("\n") : []));
        '
        exit 0
        ;;
esac

if [ "$RUN_AUTOGENERATED" = 'true' ] && [ -z "$IMAGES" ]; then
    printf '%s\n' 'No images found in the selected Features. Use --image to specify one.' >&2
    exit 1
fi

run_devcontainer() {
    set -- "$PROJECT_ROOT/node_modules/.bin/devcontainer" \
        features test --project-folder "$TEST_PROJECT_ROOT" \
        --log-level "$LOG_LEVEL" "$@"
    if [ "$QUIET" = 'true' ]; then
        set -- "$@" --quiet
    fi

    if [ "$DRY_RUN" = 'true' ]; then
        printf 'DRY RUN:'
        printf ' %s' "$@"
        printf '\n'
    else
        "$@"
    fi
}

if [ "$RUN_AUTOGENERATED" = 'true' ]; then
    for feature in $FEATURES; do
        for image in $IMAGES; do
            printf '\nAutogenerated test: Feature=%s Image=%s\n' "$feature" "$image"
            run_devcontainer \
                --features "$feature" \
                --base-image "$image" \
                --skip-scenarios
        done
    done
fi

if [ "$RUN_SCENARIOS" = 'false' ]; then
    exit 0
fi

# The Dev Container CLI only supports substring filtering for scenario names.
# It also requires a separate <scenario>.sh file for every scenario. Build a
# temporary collection so --image selects exact images and Features can use a
# single scenario.sh dispatcher instead of committing identical wrappers.
FILTERED_PROJECT="$(mktemp -d)"
ln -s "$PROJECT_ROOT/src" "$FILTERED_PROJECT/src"
mkdir -p "$FILTERED_PROJECT/test"

for feature in $FEATURES; do
    scenarios_file="$PROJECT_ROOT/test/$feature/scenarios.json"
    [ -f "$scenarios_file" ] || continue

    cp -R "$PROJECT_ROOT/test/$feature" "$FILTERED_PROJECT/test/$feature"
    filtered_scenarios="$FILTERED_PROJECT/test/$feature/scenarios.json"

    if [ "$IMAGES_EXPLICIT" = 'true' ]; then
        matching_count="$(printf '%s\n' "$IMAGES" | node -e '
            const fs = require("fs");
            const file = process.argv[1];
            const input = fs.readFileSync(0, "utf8").trim();
            const selectedImages = new Set(input ? input.split("\n") : []);
            const scenarios = JSON.parse(fs.readFileSync(file, "utf8"));
            const selected = Object.fromEntries(
                Object.entries(scenarios).filter(([, scenario]) =>
                    selectedImages.has(scenario.image),
                ),
            );
            fs.writeFileSync(file, JSON.stringify(selected, null, 2) + "\n");
            process.stdout.write(String(Object.keys(selected).length));
        ' "$filtered_scenarios")"
    else
        matching_count="$(node -e '
            const fs = require("fs");
            const scenarios = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
            process.stdout.write(String(Object.keys(scenarios).length));
        ' "$filtered_scenarios")"
    fi

    if [ "$matching_count" -eq 0 ]; then
        printf '\nNo scenarios match the selected image(s) for Feature=%s; skipping.\n' "$feature"
        continue
    fi

    scenario_dispatcher="$FILTERED_PROJECT/test/$feature/scenario.sh"
    if [ -f "$scenario_dispatcher" ]; then
        scenario_names="$(node -e '
            const fs = require("fs");
            const scenarios = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
            const names = Object.keys(scenarios);
            const invalid = names.find((name) => !/^[A-Za-z0-9._-]+$/.test(name));
            if (invalid) throw new Error("Unsupported scenario name: " + invalid);
            process.stdout.write(names.join("\n"));
        ' "$filtered_scenarios")"
        for scenario_name in $scenario_names; do
            scenario_script="$FILTERED_PROJECT/test/$feature/${scenario_name}.sh"
            if [ ! -f "$scenario_script" ]; then
                cp "$scenario_dispatcher" "$scenario_script"
            fi
        done
    fi

    printf '\nScenario tests: Feature=%s Matched=%s\n' "$feature" "$matching_count"
    TEST_PROJECT_ROOT="$FILTERED_PROJECT"
    run_devcontainer \
        --features "$feature" \
        --skip-autogenerated \
        --skip-duplicated
    TEST_PROJECT_ROOT="$PROJECT_ROOT"
done
