#!/bin/sh
set -eu

PROJECT_ROOT="$(CDPATH='' cd -- "$(dirname "$0")/../.." && pwd)"
TEST_ROOT="$(mktemp -d)"
trap 'rm -rf "$TEST_ROOT"' EXIT HUP INT TERM

FEATURE_OPTIONS="${TEST_ROOT}/options"
STORAGE_ROOT="${TEST_ROOT}/storage"
CUSTOM_HOME="${TEST_ROOT}/home/.codex"
EXTERNAL_ROOT="${TEST_ROOT}/external-codex"
NO_FIX_ROOT="${TEST_ROOT}/no-fix-codex"
CODESPACES_HOME="${TEST_ROOT}/workspaces/.codex"
MOCK_BIN="${TEST_ROOT}/bin"
MOCK_CODE_LOG="${TEST_ROOT}/code.log"
MOCK_VSCODE_ROOT="${TEST_ROOT}/vscode-server"
INSTALL_ROOT="${TEST_ROOT}/install"
MOCK_INSTALLER_LOG="${TEST_ROOT}/installer.log"
FEATURE_TEST_OUTPUT="${TEST_ROOT}/feature-tests.log"

test "$(sh "$PROJECT_ROOT/test/features/run.sh" --list-features)" = 'codex'

image_count="$(
    sh "$PROJECT_ROOT/test/features/run.sh" --list-images-json |
        node -e 'process.stdin.once("data", data => process.stdout.write(String(JSON.parse(data).length)))'
)"
test "$image_count" -eq 22

sh "$PROJECT_ROOT/test/features/run.sh" \
    --feature codex \
    --image ubuntu:24.04 \
    --dry-run >"$FEATURE_TEST_OUTPUT"
grep -F 'Autogenerated test: Feature=codex Image=ubuntu:24.04' "$FEATURE_TEST_OUTPUT" >/dev/null
grep -F 'Scenario tests: Feature=codex Matched=1' "$FEATURE_TEST_OUTPUT" >/dev/null
test "$(grep -c '^DRY RUN:' "$FEATURE_TEST_OUTPUT")" -eq 2

mkdir -p "$FEATURE_OPTIONS" "$STORAGE_ROOT/per-container" "$STORAGE_ROOT/shared" \
    "$(dirname "$CUSTOM_HOME")" "$MOCK_BIN"
touch "$STORAGE_ROOT/shared/restricted-state.json"
touch "$STORAGE_ROOT/shared/executable-tool"
chmod 0600 "$STORAGE_ROOT/shared/restricted-state.json"
chmod 0700 "$STORAGE_ROOT/shared/executable-tool"

printf '%s' "$CUSTOM_HOME" >"$FEATURE_OPTIONS/codex-home"
printf '%s' "$STORAGE_ROOT/shared" >"$FEATURE_OPTIONS/volume-path"
printf '%s' 'true' >"$FEATURE_OPTIONS/fix-permissions"
printf '%s' 'auto' >"$FEATURE_OPTIONS/permissions-owner"
printf '%s' 'auto' >"$FEATURE_OPTIONS/directory-mode"
printf '%s' 'auto' >"$FEATURE_OPTIONS/file-mode"

CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    CODEX_FEATURE_STORAGE_ROOT="$STORAGE_ROOT" \
    sh "$PROJECT_ROOT/src/codex/configure.sh"

test "$(readlink "$STORAGE_ROOT/active")" = "$STORAGE_ROOT/shared"
test "$(stat -c '%a' "$STORAGE_ROOT/shared")" = '777'
test "$(stat -c '%a' "$STORAGE_ROOT/shared/restricted-state.json")" = '666'
test "$(stat -c '%a' "$STORAGE_ROOT/shared/executable-tool")" = '777'
test "$(readlink "$CUSTOM_HOME")" = "$STORAGE_ROOT/active"

mkdir -p "$EXTERNAL_ROOT/sessions"
touch "$EXTERNAL_ROOT/auth.json" "$EXTERNAL_ROOT/executable-tool"
chmod 0755 "$EXTERNAL_ROOT" "$EXTERNAL_ROOT/sessions"
chmod 0000 "$EXTERNAL_ROOT/auth.json"
chmod 0700 "$EXTERNAL_ROOT/executable-tool"
printf '%s' "$EXTERNAL_ROOT" >"$FEATURE_OPTIONS/volume-path"

CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    CODEX_FEATURE_STORAGE_ROOT="$STORAGE_ROOT" \
    sh "$PROJECT_ROOT/src/codex/configure.sh"

test "$(readlink "$STORAGE_ROOT/active")" = "$EXTERNAL_ROOT"
test "$(stat -c '%a' "$EXTERNAL_ROOT")" = '700'
test "$(stat -c '%a' "$EXTERNAL_ROOT/sessions")" = '700'
test "$(stat -c '%a' "$EXTERNAL_ROOT/auth.json")" = '600'
test "$(stat -c '%a' "$EXTERNAL_ROOT/executable-tool")" = '700'

printf '%s' "$(id -u):$(id -g)" >"$FEATURE_OPTIONS/permissions-owner"
printf '%s' '0750' >"$FEATURE_OPTIONS/directory-mode"
printf '%s' '0640' >"$FEATURE_OPTIONS/file-mode"

CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    CODEX_FEATURE_STORAGE_ROOT="$STORAGE_ROOT" \
    sh "$PROJECT_ROOT/src/codex/configure.sh"

test "$(stat -c '%a' "$EXTERNAL_ROOT")" = '750'
test "$(stat -c '%a' "$EXTERNAL_ROOT/auth.json")" = '640'

mkdir -p "$NO_FIX_ROOT"
touch "$NO_FIX_ROOT/auth.json"
chmod 0755 "$NO_FIX_ROOT"
chmod 0644 "$NO_FIX_ROOT/auth.json"
printf '%s' "$NO_FIX_ROOT" >"$FEATURE_OPTIONS/volume-path"
printf '%s' 'false' >"$FEATURE_OPTIONS/fix-permissions"

CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    CODEX_FEATURE_STORAGE_ROOT="$STORAGE_ROOT" \
    sh "$PROJECT_ROOT/src/codex/configure.sh"

test "$(readlink "$STORAGE_ROOT/active")" = "$NO_FIX_ROOT"
test "$(stat -c '%a' "$NO_FIX_ROOT")" = '755'
test "$(stat -c '%a' "$NO_FIX_ROOT/auth.json")" = '644'

mkdir -p "$(dirname "$CODESPACES_HOME")"
printf '%s' "$CODESPACES_HOME" >"$FEATURE_OPTIONS/volume-path"

CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    CODEX_FEATURE_STORAGE_ROOT="$STORAGE_ROOT" \
    CODEX_FEATURE_CODESPACES_HOME="$CODESPACES_HOME" \
    sh "$PROJECT_ROOT/src/codex/configure.sh"

test -d "$CODESPACES_HOME"
test "$(readlink "$STORAGE_ROOT/active")" = "$CODESPACES_HOME"

cp "$PROJECT_ROOT/test/unit/mock-code.sh" "$MOCK_BIN/code"
chmod +x "$MOCK_BIN/code"

printf '%s' '1.2.3' >"$FEATURE_OPTIONS/extension-version"
PATH="$MOCK_BIN:$PATH" \
    MOCK_CODE_LOG="$MOCK_CODE_LOG" \
    CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    sh "$PROJECT_ROOT/src/codex/install-extension.sh"

expected_arguments='--install-extension
openai.chatgpt@1.2.3
--force'
test "$(cat "$MOCK_CODE_LOG")" = "$expected_arguments"

printf '%s' 'none' >"$FEATURE_OPTIONS/extension-version"
: >"$MOCK_CODE_LOG"
PATH="$MOCK_BIN:$PATH" \
    MOCK_CODE_LOG="$MOCK_CODE_LOG" \
    CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    sh "$PROJECT_ROOT/src/codex/install-extension.sh"
test ! -s "$MOCK_CODE_LOG"

printf '%s' 'latest' >"$FEATURE_OPTIONS/extension-version"
: >"$MOCK_CODE_LOG"
PATH="$MOCK_BIN:$PATH" \
    MOCK_CODE_LOG="$MOCK_CODE_LOG" \
    MOCK_CODE_VERSION_STATUS=127 \
    VSCODE_CWD="${TEST_ROOT}/missing-vscode-server" \
    CODEX_FEATURE_VSCODE_ROOTS="${TEST_ROOT}/missing-vscode-roots" \
    CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    sh "$PROJECT_ROOT/src/codex/install-extension.sh"
test ! -s "$MOCK_CODE_LOG"

mkdir -p "${MOCK_VSCODE_ROOT}/current/bin"
cp "$PROJECT_ROOT/test/unit/mock-code.sh" \
    "${MOCK_VSCODE_ROOT}/current/bin/code-server"
chmod +x "${MOCK_VSCODE_ROOT}/current/bin/code-server"
: >"$MOCK_CODE_LOG"
PATH="$MOCK_BIN:$PATH" \
    MOCK_CODE_LOG="$MOCK_CODE_LOG" \
    MOCK_CODE_VERSION_STATUS=127 \
    MOCK_CODE_SERVER_VERSION_STATUS=0 \
    VSCODE_CWD="${TEST_ROOT}/missing-vscode-server" \
    CODEX_FEATURE_VSCODE_ROOTS="$MOCK_VSCODE_ROOT" \
    CODEX_FEATURE_DIR="$FEATURE_OPTIONS" \
    sh "$PROJECT_ROOT/src/codex/install-extension.sh"
test "$(cat "$MOCK_CODE_LOG")" = '--install-extension
openai.chatgpt
--force'

mkdir -p "$INSTALL_ROOT/home"
CLIVERSION='9.8.7' \
    EXTENSIONVERSION='none' \
    INSTALLTOOLS='false' \
    VOLUMEPATH="$INSTALL_ROOT/storage/per-container" \
    FIXPERMISSIONS='true' \
    PERMISSIONSOWNER='auto' \
    DIRECTORYMODE='auto' \
    FILEMODE='auto' \
    CODEX_INSTALLER_URL="file://${PROJECT_ROOT}/test/unit/mock-installer.sh" \
    MOCK_INSTALLER_LOG="$MOCK_INSTALLER_LOG" \
    CODEX_FEATURE_DIR="$INSTALL_ROOT/feature" \
    CODEX_FEATURE_CLI_ROOT="$INSTALL_ROOT/cli" \
    CODEX_FEATURE_BIN_LINK="$INSTALL_ROOT/bin/codex" \
    CODEX_FEATURE_STORAGE_ROOT="$INSTALL_ROOT/storage" \
    _REMOTE_USER="$(id -un)" \
    _REMOTE_USER_HOME="$INSTALL_ROOT/home" \
    sh "$PROJECT_ROOT/src/codex/install.sh"

test "$(cat "$MOCK_INSTALLER_LOG")" = '9.8.7'
test "$(readlink "$INSTALL_ROOT/bin/codex")" = "$INSTALL_ROOT/cli/bin/codex"
test "$(readlink "$INSTALL_ROOT/storage/active")" = "$INSTALL_ROOT/storage/per-container"
test "$(cat "$INSTALL_ROOT/feature/volume-path")" = "$INSTALL_ROOT/storage/per-container"
test "$(readlink "$INSTALL_ROOT/home/.codex")" = "$INSTALL_ROOT/storage/active"

printf 'Unit tests passed.\n'
